version: '3.8'

services:
  user-frontend:
    build: .
    container_name: user-frontend
    restart: always
    ports:
      - "5004:80"  # OK: 5004 (VPS) → 80 (trong container)
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge