version: '3.8'

services:
  frontend:
    build: .
    container_name: user-frontend
    restart: always
    ports:
      - "5004:80"   # ← Cloudflare vào đây luôn!
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge