version: '3.8'

services:
  user-frontend:
    build: .
    container_name: user-frontend
    restart: always
    ports:
      - "5004:80" # 5004 trên VPS sẽ map tới Nginx port 80
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge
