version: '3.8'

services:
  frontend:
    build: .
    container_name: admin-frontend
    restart: always
    ports:
      - "5005:80"   # ← Cloudflare vào đây luôn!
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge